config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index'
  
  get '/pages/index', to: 'pages#index'

  get '/pages/about', to: 'pages#about'

  get '/pages/contact', to: 'contacts#new'

  get "/contacts" => redirect("/contacts/new")
  resources 'contacts', only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message

  # Declare e-mail headers. Accepts same as mail method in ActionMailer.
  def headers
    {
        :subject => "My Contact Form",
        :to => ENV['GMAIL_USERNAME'],
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.keep[:notice] = 'Thank you for your message. We will contact you soon!'
      redirect_to root_url
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end

  def contacts_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Reference: https://coderwall.com/p/d1vplg/embedding-and-styling-inline-svg-documents-with-css-in-rails
  def embedded_svg filename, options={}
    file = File.read(Rails.root.join('app', 'assets', 'images', filename))
    puts file
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] = options[:class]
    end
    doc.to_html.html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="simple-form-container">
  <h3>Send message</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
      <%= f.input :name, :required => true %>
      <%= f.input :email, :required => true %>
      <%= f.input :message, :as => :text, :required => true %>
      <div class="form-actions">
        <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Videotube</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/nav" %>
    <%= render "shared/flash" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/_related.html.erb
<!-- Related Projects Row -->
<h3 class="my-4">Related Projects</h3>

<div class="row">

  <div class="col-md-3 col-sm-6 mb-4">
    <a href="#">
      <img class="img-fluid" src="http://placehold.it/500x300" alt="">
    </a>
  </div>

  <div class="col-md-3 col-sm-6 mb-4">
    <a href="#">
      <img class="img-fluid" src="http://placehold.it/500x300" alt="">
    </a>
  </div>

  <div class="col-md-3 col-sm-6 mb-4">
    <a href="#">
      <img class="img-fluid" src="http://placehold.it/500x300" alt="">
    </a>
  </div>

  <div class="col-md-3 col-sm-6 mb-4">
    <a href="#">
      <img class="img-fluid" src="http://placehold.it/500x300" alt="">
    </a>
  </div>

</div>
<!-- /.row -->

app/views/pages/_tech.html.erb
<h3 class="my-4">Technologies</h3>

<div class="row">

  <div class="col-md-3 col-sm-6 mb-4 tech">
    <a href="#"><%= image_tag "react_icon.png", class: 'img-fluid', id: 'react', alt: 'React' %></a>
  </div>

  <div class="col-md-3 col-sm-6 mb-4 tech">
    <a href="#"><%= image_tag "ruby_icon.png", class: 'img-fluid', id: 'ruby', alt: 'Ruby' %></a>
  </div>

  <div class="col-md-3 col-sm-6 mb-4 tech">
    <a href="#"><%= image_tag "python_icon.png", class: 'img-fluid', id: 'python', alt: 'Python' %></a>
  </div>

  <div class="col-md-3 col-sm-6 mb-4 tech">
    <a href="#"><%= image_tag "node_icon.png", class: 'img-fluid tech', id: 'node', alt: 'Node.js' %></a>
  </div>

  <div class="col-md-3 col-sm-6 mb-4 tech">
    <a href="#"><%= image_tag "ethereum_icon.png", class: 'img-fluid tech', id: 'ethereum', alt: 'Ethereum' %></a>
  </div>

  <div class="col-md-3 col-sm-6 mb-4 tech">
    <a href="#"><%= image_tag "rails_icon.png", class: 'img-fluid tech', id: 'rails', alt: 'Rails' %></a>
  </div>

  <div class="col-md-3 col-sm-6 mb-4 tech">
    <a href="#"><%= image_tag "sass_icon.png", class: 'img-fluid tech', id: 'sass', alt: 'Sass' %></a>
  </div>
</div>
<!-- /.row -->

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<!-- Page Content -->
<div class="container">

  <!-- Portfolio Item Heading -->
  <!--<h1 class="my-4">Page Heading</h1>-->

  <%= render "page_item" %>

  <%= render "tech" %>

</div>
<!-- /.container -->

app/views/shared/_flash.html.erb
<div>
  <% flash.each do |name, msg| %>
      <% name = "alert-#{name}" %>
      <%= content_tag :div, msg, class: name %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Luke Schoen 2017. ABN: 49 881 416 287</p>
  </div>
</footer>

app/views/shared/_nav.html.erb
<!-- Reference: https://github.com/BlackrockDigital/startbootstrap-portfolio-item/blob/master/index.html -->

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">CEENOS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to "Home", pages_index_path, class: "nav-link" %>
        </li>
        <!--<li class="nav-item">-->
          <!--<%#= link_to "About", pages_about_path, class: "nav-link" %>-->
        <!--</li>-->
        <li class="nav-item">
          <%#= link_to "Contact", new_contact_path, class: "nav-link" %>
          <%= link_to "Contact", "mailto:ltfschoen@gmail.com", target: "_blank", class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>